name: hireshikshak

services:
  backend:
    image: hireshikshak_backend
    container_name: hireshikshak_nodejs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: ./.dev.env
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json

  nginx:
    image: nginx:latest
    container_name: hireshikshak_nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3050:80"
    depends_on:
      - backend
